change ssid error return 1

diff --git a/bella-ap/bella-ap b/bella-ap/bella-ap
--- a/bella-ap/bella-ap
+++ b/bella-ap/bella-ap
@@ -14,20 +14,20 @@ if [ "$1" = "start" ]; then
 
         # Check if Bella AP SSID and Password are set
         if [ -z "$BELLA_SSID" ] || [ -z "$BELLA_PASSWORD" ]; then
-            echo "Bella AP SSID or Password not set in Configuration File: $CONFIG_FILE"
+            echo "Warning: Bella AP SSID or Password not set in Configuration File: $CONFIG_FILE"
             exit 0
         fi
 
         # Check if SSID and Password are too long
         if [ ${#BELLA_SSID} -gt 32 ] || [ ${#BELLA_PASSWORD} -gt 64 ]; then
             echo "SSID or Password is too long. Maximum length is 32 for SSID and 64 for Password."
-            exit 0
+            exit 1
         fi
 
         # Check if SSID and Password are too short
         if [ ${#BELLA_SSID} -lt 1 ] || [ ${#BELLA_PASSWORD} -lt 8 ]; then
             echo "SSID or Password is too short. Minimum length is 1 for SSID and 8 for Password."
-            exit 0
+            exit 1
         fi
 
         # Start Bella AP
@@ -35,7 +35,7 @@ if [ "$1" = "start" ]; then
         nmcli device wifi hotspot ssid $BELLA_SSID password $BELLA_PASSWORD
 
     else
-        echo "Configuration File not found: $CONFIG_FILE"
+        echo "Warning: Configuration File not found: $CONFIG_FILE"
         exit 0
     fi
 
